export const BROKER_SPECIALTIES = [
  "Residential",
  "Commercial",
  "Industrial",
  "Agricultural / Farm",
  "Condominium",
  "Subdivision",
  "Pre-selling",
  "Foreclosed Properties",
  "Leasing",
  "Property Management",
];

export const LAWYER_SPECIALTIES = [
  "Title Transfer (Deed of Sale)",
  "Property Due Diligence",
  "Ejectment / Unlawful Detainer",
  "Foreclosure Proceedings",
  "Lease Agreement Drafting",
  "Mortgage / Loan",
  "Estate & Succession",
  "Subdivision & Condo Act",
  "Expropriation",
  "Notarial Services",
  "BIR / Tax Clearance",
  "Registry of Deeds",
  "Adverse Claim & Annotation",
  "Partition of Property",
  "HLURB / DHSUD Compliance",
];

export const REALTOR_BOARDS = [
  "PAREB - Metro Manila",
  "PAREB - Makati",
  "PAREB - Quezon City",
  "PAREB - Manila",
  "PAREB - Cebu",
  "PAREB - Davao",
  "PAREB - Iloilo",
  "PAREB - Cagayan de Oro",
  "PAREB - Bacolod",
  "PAREB - Laguna",
  "PAREB - Cavite",
  "PAREB - Bulacan",
  "CREA - Cebu",
  "REBAP - Manila",
  "REBAP - Cebu",
  "Other",
];

export const IBP_CHAPTERS = [
  "IBP Makati City Chapter",
  "IBP Taguig Chapter",
  "IBP Pasig City Chapter",
  "IBP Quezon City Chapter",
  "IBP Manila Chapter",
  "IBP Mandaluyong Chapter",
  "IBP Parañaque Chapter",
  "IBP Muntinlupa Chapter",
  "IBP Las Piñas Chapter",
  "IBP Pasay City Chapter",
  "IBP Cebu City Chapter",
  "IBP Northern Cebu Chapter",
  "IBP Davao City Chapter",
  "IBP Iloilo City Chapter",
  "IBP Bacolod City Chapter",
  "IBP Cagayan de Oro Chapter",
  "IBP Zamboanga City Chapter",
  "IBP Bulacan Chapter",
  "IBP Cavite Chapter",
  "IBP Laguna Chapter",
  "IBP Rizal Chapter",
  "Other",
];

export const PROFESSIONAL_LABELS: Record<string, { label: string; short: string; color: string; bg: string }> = {
  BROKER: {
    label: "Licensed Real Estate Broker",
    short: "Broker",
    color: "text-blue-700",
    bg: "bg-blue-100",
  },
  SALESPERSON: {
    label: "Licensed Real Estate Salesperson",
    short: "Salesperson",
    color: "text-green-700",
    bg: "bg-green-100",
  },
  LAWYER: {
    label: "Real Estate Lawyer",
    short: "Lawyer",
    color: "text-purple-700",
    bg: "bg-purple-100",
  },
};
